### ISSUE TITLE
Does not support Skylark (`.bzl`) files

### ISSUE THREAD

**Issue by agnoster** [ptsurko/language-bazel#4]
Bazel allows you to specify additional rules using Skylark.

From [Skylark - Concepts](http://bazel.io/docs/skylark/concepts.html) in the Bazel docs:

> Skylark is a superset of the core build language and its syntax is a subset of Python. The following constructs have been added to the core build language: if statements, for loops, and function definitions. It is designed to be simple, thread-safe and integrated with the BUILD language. It is not a general-purpose language and most Python features are not included.

These files have a `.bzl` extension and can be loaded in BUILD files with the `load` statement.

It would be nice to have support for Skylark files included. Simply recognizing the `.bzl` extension would be a great start.

**Comment by ptsurko** [comment]
Hi @agnoster, Good point.

As a start I am thinking about using python rules for bzl files and think how we can exclude some features as creating separate rules will be too difficult.

**Comment by agnoster** [comment]
Fair! Since it's a subset of Python (as are BUILD files, actually) it should work fine for syntax highlighting - though it would obviously be ideal if it were clear which language constructs weren't supported, that seems more like a job for a linter than a syntax highlighter :-)

**Comment by agnoster** [comment]
Hi! Is this closed because implemented or closed because wontfix?

**Comment by ptsurko** [comment]
Hi @agnoster, I've added support for bzl files as python syntax.
