### ISSUE TITLE
No support for WORKSPACE files

### ISSUE THREAD

**Issue by davidsantiago** [ptsurko/language-bazel#6]
I know the language in the WORKSPACE files is not the same as in BUILD files, but it seems pretty similar. Was the omission purposeful?

**Comment by ptsurko** [comment]
Hi @davidsantiago,
It seems like WORKSPACE file is similar to BUILD except it uses some different rule names. 
I will add WORKSPACE files to be treated the same as BUILD files as we don't hardcode rule names.
